### ISSUE TITLE
Error: Cannot find module '../lib/binding/node_libcurl.node' after upgrading to node 20.x

### ISSUE THREAD

**Issue by vasilyevi** [Arthy000/gherkin-testcafe#157]
Once I updated to node v20.11.1 the execution fails 

Cannot prepare tests due to the following error:

Error: Cannot find module '../lib/binding/node_libcurl.node'
Require stack:
- /Users/test/temp/tests/node_modules/node-libcurl/dist/Easy.js
- /Users/test/temp/tests/node_modules/node-libcurl/dist/Curl.js
- /Users/test/temp/tests/node_modules/node-libcurl/dist/index.js
- /Users/test/temp/tests/hooksSetup.js
- /Users/test/temp/tests/cucumber.js
- /Users/test/temp/tests/guide-to-common/features/steps/booking.js
- /Users/test/temp/tests/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/rewire-compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/cli.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/main.js
    at Object.<anonymous> (/Users/test/temp/tests/node_modules/node-libcurl/lib/Easy.ts:10:44)
    at Object.<anonymous> (/Users/test/temp/tests/node_modules/node-libcurl/lib/Curl.ts:22:1)
    at Object.<anonymous> (/Users/test/temp/tests/node_modules/node-libcurl/lib/index.ts:11:1)
    at Object.<anonymous> (/Users/test/temp/tests/hooksSetup.js:2:1)
    at Object.<anonymous> (/Users/test/temp/tests/cucumber.js:13:1)
    at Object.<anonymous> (/Users/test/temp/tests/guide-to-common/features/steps/booking.js:8:1)
    at /Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js:292:26
    at /Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js:291:17
    at GherkinTestcafeCompiler._loadStepDefinitions (/Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js:296:5)
    at GherkinTestcafeCompiler.getTests (/Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js:150:5)
Cannot prepare tests due to the following error:

Error: Cannot find module '../lib/binding/node_libcurl.node'
Require stack:
- /Users/test/temp/tests/node_modules/node-libcurl/dist/Easy.js
- /Users/test/temp/tests/node_modules/node-libcurl/dist/Curl.js
- /Users/test/temp/tests/node_modules/node-libcurl/dist/index.js
- /Users/test/temp/tests/hooksSetup.js
- /Users/test/temp/tests/cucumber.js
- /Users/test/temp/tests/guide-to-common/features/steps/cart.js
- /Users/test/temp/tests/node_modules/testcafe/lib/compiler/test-file/formats/es-next/compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/rewire-compiler.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/src/cli.js
- /Users/test/temp/tests/node_modules/gherkin-testcafe/main.js
    at Object.<anonymous> (/Users/test/temp/tests/node_modules/node-libcurl/lib/Easy.ts:10:44)
Cannot prepare tests due to the following error:

**Comment by Arthy000** [comment]
Hi @vasilyevi, I'm going to need more information because I cannot reproduce the issue

<img width="405" alt="Screenshot 2024-03-02 at 10 31 40" src="https://github.com/Arthy000/gherkin-testcafe/assets/1800622/9f93249c-76e1-4b66-9abe-83a90cde9e2e">

I'm not even seeing the problematic library in my node_modules so these may come from another of your dependencies.
