### ISSUE TITLE
gherkin-testcafe is running in to TypeError 

### ISSUE THREAD

**Issue by raj-balaebail** [Arthy000/gherkin-testcafe#31]
Trying to get the cucumber and testcafe integration going. 

```rajbalaebail@Rajs-MacBook-Pro ~ % gherkin-testcafe firefox amount-repos/CucumberPOC/**/*.js amount-repos/CucumberPOC/**/*.feature 
ERROR Cannot prepare tests due to an error.

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at Object.getDefinitionLineAndUri (/Users/rajbalaebail/node_modules/@cucumber/cucumber/src/support_code_library_builder/build_helpers.ts:21:18)
    at SupportCodeLibraryBuilder.defineStep (/Users/rajbalaebail/node_modules/@cucumber/cucumber/src/support_code_library_builder/index.ts:133:27)
    at Object.<anonymous> (/Users/rajbalaebail/amount-repos/CucumberPOC/features/step_definitions/CF-1951.js:7:1)
    at /Users/rajbalaebail/gherkin-testcafe/src/compiler.js:243:26
    at /Users/rajbalaebail/gherkin-testcafe/src/compiler.js:242:17
    at GherkinTestcafeCompiler._loadStepDefinitions (/Users/rajbalaebail/gherkin-testcafe/src/compiler.js:247:5)
    at GherkinTestcafeCompiler.getTests (/Users/rajbalaebail/gherkin-testcafe/src/compiler.js:143:5)
```

**Comment by Arthy000** [comment]
Hello @raj-balaebail,

What version of the package are you using?
What version of TestCafe did you install?
What version of Cucumber did you install?

The error you describe is typically what you get when some of the dependencies are not met.

**Comment by raj-balaebail** [comment]
I was following the instructions in the main readme. I installed all peer dependencies that it was complaining against.
```
rajbalaebail@Rajs-MacBook-Pro ~ % npm list | grep gherkin-testcafe    
├─┬ gherkin-testcafe@4.0.0 -> /Users/rajbalaebail/gherkin-testcafe
rajbalaebail@Rajs-MacBook-Pro ~ % npm list | grep testcafe            
├─┬ gherkin-testcafe@4.0.0 -> /Users/rajbalaebail/gherkin-testcafe
└─┬ testcafe@1.13.0
  ├─┬ testcafe-browser-tools@2.0.15
  ├─┬ testcafe-hammerhead@19.5.0
  ├─┬ testcafe-legacy-api@4.2.5
  │ └── testcafe-hammerhead@19.5.0 deduped
  ├── testcafe-reporter-json@2.2.0
  ├── testcafe-reporter-list@2.1.0
  ├── testcafe-reporter-minimal@2.1.0
  ├── testcafe-reporter-spec@2.1.1
  ├── testcafe-reporter-xunit@2.1.0
rajbalaebail@Rajs-MacBook-Pro ~ % npm list | grep @cucumber/cucumber
├─┬ @cucumber/cucumber@7.0.0
│ ├─┬ @cucumber/cucumber-expressions@11.0.2
├─┬ @cucumber/cucumber-expressions@12.0.0
│ ├─┬ @cucumber/cucumber@7.0.0
│ │ ├─┬ @cucumber/cucumber-expressions@11.0.2
│ ├─┬ @cucumber/cucumber-expressions@12.0.0
```

**Comment by raj-balaebail** [comment]
PS: I can do a reinstall and clean install of all the repos if that is preferable.

**Comment by Arthy000** [comment]
Hello again,

I think I see the issue, the documentation you followed is about a version that hasn't been published yet (that's completely my fault, I set develop as the main branch but I publish/release master, I corrected that)

However the only way you got the warning you did is if you also have `cucumber` installed (as opposed to `@cucumber/cucumber`) in a version that is higher than 5.1.0

I'm releasing the new version now so you should just have tu upgrade gherkin-testcafe in a few minutes. From then it will be using `@cucumber/cucumber` and ignore whatever version of `cucumber` you have.

**Comment by Arthy000** [comment]
Bumped the version to 5.0.0 as updating cucumber was a breaking change. Can you upgrade and let me know if your issue is solved?

**Comment by raj-balaebail** [comment]
I still run in to the issue and I don't seem to have cucumber installed.
```
rajbalaebail@Rajs-MacBook-Pro ~ % npm list | grep gherkin-testcafe 
├─┬ gherkin-testcafe@5.0.0 -> /Users/rajbalaebail/gherkin-testcafe
rajbalaebail@Rajs-MacBook-Pro ~ % gherkin-testcafe firefox amount-repos/CucumberPOC/**/*.js amount-repos/CucumberPOC/**/*.feature 
ERROR Cannot prepare tests due to an error.

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at Object.getDefinitionLineAndUri (/Users/rajbalaebail/node_modules/@cucumber/cucumber/src/support_code_library_builder/build_helpers.ts:21:18)
    at SupportCodeLibraryBuilder.defineStep (/Users/rajbalaebail/node_modules/@cucumber/cucumber/src/support_code_library_builder/index.ts:133:27)
    at Object.<anonymous> (/Users/rajbalaebail/amount-repos/CucumberPOC/test/features/step_definitions/CF-1951.js:7:1)
    at /Users/rajbalaebail/gherkin-testcafe/src/compiler.js:243:26
    at /Users/rajbalaebail/gherkin-testcafe/src/compiler.js:242:17
    at GherkinTestcafeCompiler._loadStepDefinitions (/Users/rajbalaebail/gherkin-testcafe/src/compiler.js:247:5)
    at GherkinTestcafeCompiler.getTests (/Users/rajbalaebail/gherkin-testcafe/src/compiler.js:143:5)

Type "testcafe -h" for help.
rajbalaebail@Rajs-MacBook-Pro ~ % npm list | grep cucumber        
├─┬ @cucumber/cucumber@7.0.0
│ ├─┬ @cucumber/create-meta@2.0.4
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├─┬ @cucumber/cucumber-expressions@11.0.2
│ ├─┬ @cucumber/gherkin@16.0.0
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├─┬ @cucumber/html-formatter@11.0.4
│ │ ├─┬ @cucumber/gherkin-utils@2.1.1
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├── @cucumber/query@7.0.1 deduped
│ │ ├─┬ @cucumber/react@11.0.2
│ │ │ ├── @cucumber/gherkin-utils@2.1.1 deduped
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ │ ├── @cucumber/query@7.0.1 deduped
│ │ │ ├── @cucumber/tag-expressions@2.0.4 deduped
│ ├─┬ @cucumber/messages@13.2.1
│ ├─┬ @cucumber/query@7.0.1
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├── @cucumber/tag-expressions@2.0.4
├─┬ @cucumber/cucumber-expressions@12.0.0
│ ├─┬ @cucumber/cucumber@7.0.0
│ │ ├─┬ @cucumber/create-meta@2.0.4
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├─┬ @cucumber/cucumber-expressions@11.0.2
│ │ ├─┬ @cucumber/gherkin@16.0.0
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├─┬ @cucumber/html-formatter@11.0.4
│ │ │ ├─┬ @cucumber/gherkin-utils@2.1.1
│ │ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ │ ├── @cucumber/query@7.0.1 deduped
│ │ │ ├─┬ @cucumber/react@11.0.2
│ │ │ │ ├── @cucumber/gherkin-utils@2.1.1 deduped
│ │ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ │ │ ├── @cucumber/query@7.0.1 deduped
│ │ │ │ ├── @cucumber/tag-expressions@2.0.4 deduped
│ │ ├─┬ @cucumber/messages@13.2.1
│ │ ├─┬ @cucumber/query@7.0.1
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├── @cucumber/tag-expressions@2.0.4
│ ├─┬ @cucumber/cucumber-expressions@12.0.0
│   ├─┬ cucumber-messages@7.0.0
```

**Comment by Arthy000** [comment]
I created a project from scratch on my Mac, no issue :(

Your dependency tree seems a bit messed up compared to mine.
```
~/gherkin-testcafe-tester $ npm list | grep cucumber
├─┬ @cucumber/cucumber@7.0.0
│ ├─┬ @cucumber/create-meta@2.0.4
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├─┬ @cucumber/cucumber-expressions@11.0.2
│ ├─┬ @cucumber/gherkin@16.0.0
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├─┬ @cucumber/html-formatter@11.0.4
│ │ ├─┬ @cucumber/gherkin-utils@2.1.1
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├── @cucumber/messages@13.2.1 deduped
│ │ ├── @cucumber/query@7.0.1 deduped
│ │ ├─┬ @cucumber/react@11.0.2
│ │ │ ├── @cucumber/gherkin-utils@2.1.1 deduped
│ │ │ ├── @cucumber/messages@13.2.1 deduped
│ │ │ ├── @cucumber/query@7.0.1 deduped
│ │ │ ├── @cucumber/tag-expressions@2.0.4 deduped
│ ├─┬ @cucumber/messages@13.2.1
│ ├─┬ @cucumber/query@7.0.1
│ │ ├── @cucumber/messages@13.2.1 deduped
│ ├── @cucumber/tag-expressions@2.0.4
├─┬ @cucumber/cucumber-expressions@12.0.0
│ ├── @cucumber/cucumber@7.0.0 deduped
│ ├── @cucumber/cucumber-expressions@12.0.0 deduped
│   ├─┬ cucumber-messages@7.0.0
```

First thing to try is to rebuild your node_modules from scratch.

If that doesn't work, may I see your `package.json`?

**Comment by Arthy000** [comment]
AHA ! 
Found something, are your features/steps files located in a folder outside of your project?

https://github.com/kiwigrid/gherkin-testcafe/issues/45

**Comment by raj-balaebail** [comment]
```  "dependencies": {
    "@cucumber/cucumber": "^7.0.0",
    "@cucumber/cucumber-expressions": "^12.0.0",
    "@types/react": "^17.0.3",
    "gherkin-testcafe": "file:gherkin-testcafe",
    "react-markdown": "^5.0.3",
    "testcafe": "^1.13.0"
  },
  "devDependencies": {}
}
```

**Comment by raj-balaebail** [comment]
My package.json is in my home directory and the tests are nested three directories within my home directory.

**Comment by Arthy000** [comment]
When you say home directory, do you mean the home directory of your project or the home directory of your user?

**Comment by raj-balaebail** [comment]
User home directory

**Comment by raj-balaebail** [comment]
I seem to have gotten past this error after uninstalling all copies of cucumber, gherkin, gherkin-testcafe and reinstalling it. I am running in to other errors in the code though that I will look at. Thanks for the help !!

**Comment by Arthy000** [comment]
You're welcome :) 
If I were you I'd create a project directory and use local (installed without -g) versions of the packages. It will prevent interactions between packages that were installed for other reasons.
