### ISSUE TITLE
Cannot find module from fresh install

### ISSUE THREAD

**Issue by rkim-work** [Arthy000/gherkin-testcafe#33]
Hi, I am having trouble on a fresh install : 

`mkdir bdd; cd bdd; yarn add gherkin-testcafe @cucumber/cucumber`
`./node_modules/.bin/gherkin-testcafe --help`

**Produces the error :** 
```
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'testcafe/lib/api/structure/fixture'
Require stack:
- /Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/compiler.js
- /Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/rewire-compiler.js
- /Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/cli.js
- /Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/main.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/compiler.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/compiler.js',
    '/Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/rewire-compiler.js',
    '/Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/src/cli.js',
    '/Users/rkim/Sites/bdd/node_modules/gherkin-testcafe/main.js'
  ]
}
```

**My dependencies :** 
```
cat package.json
{
  "dependencies": {
    "@cucumber/cucumber": "^7.0.0",
    "gherkin-testcafe": "^5.0.0"
  }
}
```

```
yarn list
yarn list v1.7.0
warning package.json: No license field
warning No license field
├─ @cucumber/create-meta@2.0.4
│  ├─ @cucumber/messages@^13.1.0
│  ├─ ts-node@^9.0.0
│  └─ typescript@^4.0.5
├─ @cucumber/cucumber-expressions@11.0.2
│  └─ becke-ch--regex--s0-0-v1--base--pl--lib@^1.4.0
├─ @cucumber/cucumber@7.0.0
│  ├─ @cucumber/create-meta@^2.0.4
│  ├─ @cucumber/cucumber-expressions@^11.0.0
│  ├─ @cucumber/gherkin@^16.0.0
│  ├─ @cucumber/html-formatter@^11.0.4
│  ├─ @cucumber/messages@^13.2.1
│  ├─ @cucumber/query@^7.0.1
│  ├─ @cucumber/tag-expressions@^2.0.4
│  ├─ assertion-error-formatter@^3.0.0
│  ├─ bluebird@^3.7.2
│  ├─ capital-case@^1.0.4
│  ├─ cli-table3@^0.6.0
│  ├─ colors@^1.4.0
│  ├─ commander@^6.2.1
│  ├─ create-require@^1.1.1
│  ├─ duration@^0.2.2
│  ├─ durations@^3.4.2
│  ├─ figures@^3.2.0
│  ├─ glob@^7.1.6
│  ├─ indent-string@^4.0.0
│  ├─ is-generator@^1.0.3
│  ├─ is-stream@^2.0.0
│  ├─ knuth-shuffle-seeded@^1.0.6
│  ├─ lodash@^4.17.20
│  ├─ mz@^2.7.0
│  ├─ progress@^2.0.3
│  ├─ resolve-pkg@^2.0.0
│  ├─ resolve@^1.19.0
│  ├─ stack-chain@^2.0.0
│  ├─ stacktrace-js@^2.0.2
│  ├─ string-argv@^0.3.1
│  ├─ tmp@^0.2.1
│  ├─ util-arity@^1.1.0
│  └─ verror@^1.10.0
├─ @cucumber/gherkin-utils@2.1.1
│  ├─ @cucumber/messages@^13.2.1
│  └─ @teppeis/multimaps@^1.1.0
├─ @cucumber/gherkin@16.0.0
│  ├─ @cucumber/messages@^13.2.1
│  ├─ commander@^6.2.0
│  └─ source-map-support@^0.5.19
├─ @cucumber/html-formatter@11.0.4
│  ├─ @cucumber/gherkin-utils@^2.1.1
│  ├─ @cucumber/messages@^13.2.1
│  ├─ @cucumber/query@^7.0.1
│  ├─ @cucumber/react@^11.0.2
│  ├─ commander@^6.2.1
│  ├─ react-dom@^17.0.1
│  ├─ react@^17.0.1
│  ├─ resolve-pkg@^2.0.0
│  └─ source-map-support@^0.5.19
├─ @cucumber/messages@13.2.1
│  ├─ @types/uuid@^8.3.0
│  ├─ protobufjs@^6.10.2
│  ├─ uuid@^8.3.1
│  └─ uuid@8.3.2
├─ @cucumber/query@7.0.1
│  ├─ @cucumber/messages@^13.2.1
│  └─ @teppeis/multimaps@^1.1.0
├─ @cucumber/react@11.0.2
│  ├─ @cucumber/gherkin-utils@^2.1.1
│  ├─ @cucumber/messages@^13.2.1
│  ├─ @cucumber/query@^7.0.1
│  ├─ @cucumber/tag-expressions@^2.0.4
│  ├─ @fortawesome/fontawesome-svg-core@^1.2.32
│  ├─ @fortawesome/free-solid-svg-icons@^5.15.1
│  ├─ @fortawesome/react-fontawesome@^0.1.13
│  ├─ @teppeis/multimaps@^1.1.0
│  ├─ @types/elasticlunr@^0.9.1
│  ├─ ansi-to-html@^0.6.14
│  ├─ color@^3.1.3
│  ├─ elasticlunr@^0.9.5
│  ├─ highlight-words@^1.0.6
│  ├─ react-accessible-accordion@^3.3.3
│  └─ react-markdown@^5.0.3
├─ @cucumber/tag-expressions@2.0.4
├─ @fortawesome/fontawesome-common-types@0.2.35
├─ @fortawesome/fontawesome-svg-core@1.2.35
│  └─ @fortawesome/fontawesome-common-types@^0.2.35
├─ @fortawesome/free-solid-svg-icons@5.15.3
│  └─ @fortawesome/fontawesome-common-types@^0.2.35
├─ @fortawesome/react-fontawesome@0.1.14
│  └─ prop-types@^15.7.2
├─ @protobufjs/aspromise@1.1.2
├─ @protobufjs/base64@1.1.2
├─ @protobufjs/codegen@2.0.4
├─ @protobufjs/eventemitter@1.1.0
├─ @protobufjs/fetch@1.1.0
│  ├─ @protobufjs/aspromise@^1.1.1
│  └─ @protobufjs/inquire@^1.1.0
├─ @protobufjs/float@1.0.2
├─ @protobufjs/inquire@1.1.0
├─ @protobufjs/path@1.1.2
├─ @protobufjs/pool@1.1.0
├─ @protobufjs/utf8@1.1.0
├─ @teppeis/multimaps@1.1.0
├─ @types/elasticlunr@0.9.1
├─ @types/long@4.0.1
├─ @types/mdast@3.0.3
│  └─ @types/unist@*
├─ @types/node@13.13.47
├─ @types/unist@2.0.3
├─ @types/uuid@8.3.0
├─ ansi-regex@5.0.0
├─ ansi-to-html@0.6.14
│  ├─ entities@^1.1.2
│  └─ entities@1.1.2
├─ any-promise@1.3.0
├─ arg@4.1.3
├─ assert-plus@1.0.0
├─ assertion-error-formatter@3.0.0
│  ├─ diff@^4.0.1
│  ├─ pad-right@^0.2.2
│  └─ repeat-string@^1.6.1
├─ bail@1.0.5
├─ balanced-match@1.0.0
├─ becke-ch--regex--s0-0-v1--base--pl--lib@1.4.0
├─ bluebird@3.7.2
├─ brace-expansion@1.1.11
│  ├─ balanced-match@^1.0.0
│  └─ concat-map@0.0.1
├─ buffer-from@1.1.1
├─ capital-case@1.0.4
│  ├─ no-case@^3.0.4
│  ├─ tslib@^2.0.3
│  └─ upper-case-first@^2.0.2
├─ character-entities-legacy@1.1.4
├─ character-entities@1.2.4
├─ character-reference-invalid@1.1.4
├─ cli-table3@0.6.0
│  ├─ colors@^1.1.2
│  ├─ object-assign@^4.1.0
│  └─ string-width@^4.2.0
├─ color-convert@1.9.3
│  └─ color-name@1.1.3
├─ color-name@1.1.3
├─ color-string@1.5.5
│  ├─ color-name@^1.0.0
│  ├─ color-name@1.1.4
│  └─ simple-swizzle@^0.2.2
├─ color@3.1.3
│  ├─ color-convert@^1.9.1
│  └─ color-string@^1.5.4
├─ colors@1.4.0
├─ commander@6.2.1
├─ concat-map@0.0.1
├─ core-util-is@1.0.2
├─ create-require@1.1.1
├─ cucumber-messages@7.0.0
│  └─ protobufjs@^6.8.8
├─ d@1.0.1
│  ├─ es5-ext@^0.10.50
│  └─ type@^1.0.1
├─ debug@4.3.1
│  └─ ms@2.1.2
├─ diff@4.0.2
├─ dom-serializer@1.2.0
│  ├─ domelementtype@^2.0.1
│  ├─ domhandler@^4.0.0
│  ├─ domhandler@4.0.0
│  │  └─ domelementtype@^2.1.0
│  └─ entities@^2.0.0
├─ domelementtype@2.1.0
├─ domhandler@3.3.0
│  └─ domelementtype@^2.0.1
├─ domutils@2.5.0
│  ├─ dom-serializer@^1.0.1
│  ├─ domelementtype@^2.0.1
│  ├─ domhandler@^4.0.0
│  └─ domhandler@4.0.0
│     └─ domelementtype@^2.1.0
├─ duration@0.2.2
│  ├─ d@1
│  └─ es5-ext@~0.10.46
├─ durations@3.4.2
├─ elasticlunr@0.9.5
├─ emoji-regex@8.0.0
├─ entities@2.2.0
├─ error-stack-parser@2.0.6
│  └─ stackframe@^1.1.1
├─ es5-ext@0.10.53
│  ├─ es6-iterator@~2.0.3
│  ├─ es6-symbol@~3.1.3
│  └─ next-tick@~1.0.0
├─ es6-iterator@2.0.3
│  ├─ d@1
│  ├─ es5-ext@^0.10.35
│  └─ es6-symbol@^3.1.1
├─ es6-symbol@3.1.3
│  ├─ d@^1.0.1
│  └─ ext@^1.1.2
├─ escape-string-regexp@1.0.5
├─ ext@1.4.0
│  ├─ type@^2.0.0
│  └─ type@2.5.0
├─ extend@3.0.2
├─ extsprintf@1.4.0
├─ figures@3.2.0
│  └─ escape-string-regexp@^1.0.5
├─ fs.realpath@1.0.0
├─ function-bind@1.1.1
├─ gherkin-testcafe@5.0.0
│  ├─ @cucumber/cucumber-expressions@^12.0.0
│  ├─ @cucumber/cucumber-expressions@12.0.0
│  │  └─ becke-ch--regex--s0-0-v1--base--pl--lib@^1.4.0
│  ├─ @cucumber/cucumber@^7.0.0
│  └─ gherkin@^8.1.1
├─ gherkin@8.2.1
│  ├─ cucumber-messages@7.0.0
│  ├─ source-map-support@^0.5.16
│  └─ uuid@^3.3.3
├─ glob@7.1.6
│  ├─ fs.realpath@^1.0.0
│  ├─ inflight@^1.0.4
│  ├─ inherits@2
│  ├─ minimatch@^3.0.4
│  ├─ once@^1.3.0
│  └─ path-is-absolute@^1.0.0
├─ has@1.0.3
│  └─ function-bind@^1.1.1
├─ highlight-words@1.1.0
├─ html-to-react@1.4.5
│  ├─ domhandler@^3.3.0
│  ├─ htmlparser2@^5.0
│  ├─ lodash.camelcase@^4.3.0
│  └─ ramda@^0.27.1
├─ htmlparser2@5.0.1
│  ├─ domelementtype@^2.0.1
│  ├─ domhandler@^3.3.0
│  ├─ domutils@^2.4.2
│  └─ entities@^2.0.0
├─ indent-string@4.0.0
├─ inflight@1.0.6
│  ├─ once@^1.3.0
│  └─ wrappy@1
├─ inherits@2.0.4
├─ is-alphabetical@1.0.4
├─ is-alphanumerical@1.0.4
│  ├─ is-alphabetical@^1.0.0
│  └─ is-decimal@^1.0.0
├─ is-arrayish@0.3.2
├─ is-buffer@2.0.5
├─ is-core-module@2.2.0
│  └─ has@^1.0.3
├─ is-decimal@1.0.4
├─ is-fullwidth-code-point@3.0.0
├─ is-generator@1.0.3
├─ is-hexadecimal@1.0.4
├─ is-plain-obj@2.1.0
├─ is-stream@2.0.0
├─ js-tokens@4.0.0
├─ knuth-shuffle-seeded@1.0.6
│  └─ seed-random@~2.2.0
├─ lodash.camelcase@4.3.0
├─ lodash@4.17.21
├─ long@4.0.0
├─ loose-envify@1.4.0
│  └─ js-tokens@^3.0.0 || ^4.0.0
├─ lower-case@2.0.2
│  └─ tslib@^2.0.3
├─ make-error@1.3.6
├─ mdast-add-list-metadata@1.0.1
│  └─ unist-util-visit-parents@1.1.2
├─ mdast-util-from-markdown@0.8.5
│  ├─ @types/mdast@^3.0.0
│  ├─ mdast-util-to-string@^2.0.0
│  ├─ micromark@~2.11.0
│  ├─ parse-entities@^2.0.0
│  └─ unist-util-stringify-position@^2.0.0
├─ mdast-util-to-string@2.0.0
├─ micromark@2.11.4
│  ├─ debug@^4.0.0
│  └─ parse-entities@^2.0.0
├─ minimatch@3.0.4
│  └─ brace-expansion@^1.1.7
├─ ms@2.1.2
├─ mz@2.7.0
│  ├─ any-promise@^1.0.0
│  ├─ object-assign@^4.0.1
│  └─ thenify-all@^1.0.0
├─ next-tick@1.0.0
├─ no-case@3.0.4
│  ├─ lower-case@^2.0.2
│  └─ tslib@^2.0.3
├─ object-assign@4.1.1
├─ once@1.4.0
│  └─ wrappy@1
├─ pad-right@0.2.2
│  └─ repeat-string@^1.5.2
├─ parse-entities@2.0.0
│  ├─ character-entities-legacy@^1.0.0
│  ├─ character-entities@^1.0.0
│  ├─ character-reference-invalid@^1.0.0
│  ├─ is-alphanumerical@^1.0.0
│  ├─ is-decimal@^1.0.0
│  └─ is-hexadecimal@^1.0.0
├─ path-is-absolute@1.0.1
├─ path-parse@1.0.6
├─ progress@2.0.3
├─ prop-types@15.7.2
│  ├─ loose-envify@^1.4.0
│  ├─ object-assign@^4.1.1
│  └─ react-is@^16.8.1
├─ protobufjs@6.10.2
│  ├─ @protobufjs/aspromise@^1.1.2
│  ├─ @protobufjs/base64@^1.1.2
│  ├─ @protobufjs/codegen@^2.0.4
│  ├─ @protobufjs/eventemitter@^1.1.0
│  ├─ @protobufjs/fetch@^1.1.0
│  ├─ @protobufjs/float@^1.0.2
│  ├─ @protobufjs/inquire@^1.1.0
│  ├─ @protobufjs/path@^1.1.2
│  ├─ @protobufjs/pool@^1.1.0
│  ├─ @protobufjs/utf8@^1.1.0
│  ├─ @types/long@^4.0.1
│  ├─ @types/node@^13.7.0
│  └─ long@^4.0.0
├─ ramda@0.27.1
├─ react-accessible-accordion@3.3.4
├─ react-dom@17.0.2
│  ├─ loose-envify@^1.1.0
│  ├─ object-assign@^4.1.1
│  └─ scheduler@^0.20.2
├─ react-is@16.13.1
├─ react-markdown@5.0.3
│  ├─ @types/mdast@^3.0.3
│  ├─ @types/unist@^2.0.3
│  ├─ html-to-react@^1.3.4
│  ├─ mdast-add-list-metadata@1.0.1
│  ├─ prop-types@^15.7.2
│  ├─ react-is@^16.8.6
│  ├─ remark-parse@^9.0.0
│  ├─ unified@^9.0.0
│  ├─ unist-util-visit@^2.0.0
│  └─ xtend@^4.0.1
├─ react@17.0.2
│  ├─ loose-envify@^1.1.0
│  └─ object-assign@^4.1.1
├─ remark-parse@9.0.0
│  └─ mdast-util-from-markdown@^0.8.0
├─ repeat-string@1.6.1
├─ resolve-from@5.0.0
├─ resolve-pkg@2.0.0
│  └─ resolve-from@^5.0.0
├─ resolve@1.20.0
│  ├─ is-core-module@^2.2.0
│  └─ path-parse@^1.0.6
├─ rimraf@3.0.2
│  └─ glob@^7.1.3
├─ scheduler@0.20.2
│  ├─ loose-envify@^1.1.0
│  └─ object-assign@^4.1.1
├─ seed-random@2.2.0
├─ simple-swizzle@0.2.2
│  └─ is-arrayish@^0.3.1
├─ source-map-support@0.5.19
│  ├─ buffer-from@^1.0.0
│  ├─ source-map@^0.6.0
│  └─ source-map@0.6.1
├─ source-map@0.5.6
├─ stack-chain@2.0.0
├─ stack-generator@2.0.5
│  └─ stackframe@^1.1.1
├─ stackframe@1.2.0
├─ stacktrace-gps@3.0.4
│  ├─ source-map@0.5.6
│  └─ stackframe@^1.1.1
├─ stacktrace-js@2.0.2
│  ├─ error-stack-parser@^2.0.6
│  ├─ stack-generator@^2.0.5
│  └─ stacktrace-gps@^3.0.4
├─ string-argv@0.3.1
├─ string-width@4.2.2
│  ├─ emoji-regex@^8.0.0
│  ├─ is-fullwidth-code-point@^3.0.0
│  └─ strip-ansi@^6.0.0
├─ strip-ansi@6.0.0
│  └─ ansi-regex@^5.0.0
├─ thenify-all@1.6.0
│  └─ thenify@>= 3.1.0 < 4
├─ thenify@3.3.1
│  └─ any-promise@^1.0.0
├─ tmp@0.2.1
│  └─ rimraf@^3.0.0
├─ trough@1.0.5
├─ ts-node@9.1.1
│  ├─ arg@^4.1.0
│  ├─ create-require@^1.1.0
│  ├─ diff@^4.0.1
│  ├─ make-error@^1.1.1
│  ├─ source-map-support@^0.5.17
│  └─ yn@3.1.1
├─ tslib@2.1.0
├─ type@1.2.0
├─ typescript@4.2.3
├─ unified@9.2.1
│  ├─ bail@^1.0.0
│  ├─ extend@^3.0.0
│  ├─ is-buffer@^2.0.0
│  ├─ is-plain-obj@^2.0.0
│  ├─ trough@^1.0.0
│  └─ vfile@^4.0.0
├─ unist-util-is@4.1.0
├─ unist-util-stringify-position@2.0.3
│  └─ @types/unist@^2.0.2
├─ unist-util-visit-parents@1.1.2
├─ unist-util-visit@2.0.3
│  ├─ @types/unist@^2.0.0
│  ├─ unist-util-is@^4.0.0
│  ├─ unist-util-visit-parents@^3.0.0
│  └─ unist-util-visit-parents@3.1.1
│     ├─ @types/unist@^2.0.0
│     └─ unist-util-is@^4.0.0
├─ upper-case-first@2.0.2
│  └─ tslib@^2.0.3
├─ util-arity@1.1.0
├─ uuid@3.4.0
├─ verror@1.10.0
│  ├─ assert-plus@^1.0.0
│  ├─ core-util-is@1.0.2
│  └─ extsprintf@^1.2.0
├─ vfile-message@2.0.4
│  ├─ @types/unist@^2.0.0
│  └─ unist-util-stringify-position@^2.0.0
├─ vfile@4.2.1
│  ├─ @types/unist@^2.0.0
│  ├─ is-buffer@^2.0.0
│  ├─ unist-util-stringify-position@^2.0.0
│  └─ vfile-message@^2.0.0
├─ wrappy@1.0.2
├─ xtend@4.0.2
└─ yn@3.1.1
```

```
node -v
v12.14.0
```

Any idea what's wrong?

(same thing happen on another mac)

**Comment by rkim-work** [comment]
My bad, after 
`yarn add testcafe`
its now working.

(Thought it was installed as dependency of gherkin-testcafe)
