### ISSUE TITLE
TypeError: The "from" argument must be of type string.

### ISSUE THREAD

**Issue by GregorBiswanger** [Arthy000/gherkin-testcafe#67]
Hi there,

I set up a new project and installed the following DevDependencies:

```
{
  "name": "testcafe-demo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cucumber/cucumber": "^8.0.0-rc.2",
    "@cucumber/cucumber-expressions": "^15.0.1",
    "gherkin-testcafe": "^5.1.0",
    "testcafe": "^1.18.3"
  }
}
```

I have the test code and feature file in the `e2e` folder.

Unfortunately, when I run it, I get the following error message:

```
> npx gherkin-testcafe chrome:headless e2e/**/*.ts e2e/**/*.feature
ERROR Cannot prepare tests due to the following error:

TypeError: The "from" argument must be of type string. Received undefined
    at getDefinitionLineAndUri (C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\@cucumber\cucumber\src\support_code_library_builder\get_definition_line_and_uri.ts:25:18)
    at SupportCodeLibraryBuilder.defineStep (C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\@cucumber\cucumber\src\support_code_library_builder\index.ts:134:50)
    at Object.<anonymous> (C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\e2e\company-sidebar.spec.ts:19:1)
    at C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\gherkin-testcafe\src\compiler.js:244:26
    at C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\gherkin-testcafe\src\compiler.js:243:17
    at GherkinTestcafeCompiler._loadStepDefinitions (C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\gherkin-testcafe\src\compiler.js:248:5)
    at GherkinTestcafeCompiler.getTests (C:\Users\Gregor\Documents\Web-Projects\testcafe-demo\node_modules\gherkin-testcafe\src\compiler.js:143:5)

Type "testcafe -h" for help.
```

None of this is installed globally.

**Comment by Arthy000** [comment]
Closing this, feel free to reopen if needed
