### ISSUE TITLE
gtc-reporter-spec.js attempts to reassign const

### ISSUE THREAD

**Issue by ngencokamin** [Arthy000/gherkin-testcafe#90]
Testcafe in docker started breaking with latest version, error: 

```
ERROR The "reportTestDone" method of the "gtc-reporter-spec" reporter produced an uncaught error. Error details:
--
TypeError: Assignment to constant variable.
at ReporterPluginHost.reportTestDone (/test/src/reporters/gtc-reporter-spec.js:68:41)
at Reporter.dispatchToPlugin (/node_modules/testcafe/src/reporter/index.ts:160:38)
at Reporter._shiftTestQueue (/node_modules/testcafe/src/reporter/index.ts:329:24)
at Reporter._resolveTestItem (/node_modules/testcafe/src/reporter/index.ts:393:20)
at Reporter._onTaskTestRunDoneHandler (/node_modules/testcafe/src/reporter/index.ts:539:24)
at /node_modules/testcafe/src/reporter/index.ts:185:68
at /node_modules/emittery/index.js:69:13
at Array.map (<anonymous>)
at MessageBus.emit (/node_modules/emittery/index.js:67:23)
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at /node_modules/testcafe/src/runner/task/index.ts:92:13
```

Looks like the issue comes from here [here](https://github.com/Arthy000/gherkin-testcafe/blob/ebc299e5804a1c3b06986ca7956e29d9a232cf97/src/reporters/gtc-reporter-spec.js#L62-L68), it seems `title` is initialized as a const, and then there is an attempt to change the value. I see a similar block in the testcafe-reporter-spec repo [here](https://github.com/DevExpress/testcafe-reporter-spec/blob/dcd9614ea46364ffbde07db81a6678e51303d7c7/src/index.js#L74-L83), where `title` is initialized with `var`

**Comment by Arthy000** [comment]
Hi @ngencokamin 
Thanks for the report, I'll fix it right away.

**Comment by Arthy000** [comment]
Can you try the version 5.4.1 and confirm whether it works?

**Comment by ngencokamin** [comment]
> Can you try the version 5.4.2 and confirm whether it works?

Seems to have resolved the issue, tysm for the quick fix! :D
