### ISSUE TITLE
Error when running gherkin-testcafe 5.4.3. with testcafe 1.20

### ISSUE THREAD

**Issue by eroetman** [Arthy000/gherkin-testcafe#97]
After updating both testcafé (1.20) and gherkin-testcafe (5.4.3) the following error is thrown when starting a test:

`TypeError: Cannot destructure property 'isCompilerServiceMode' of 'undefined' as it is undefined.
    at new APIBasedTestFileCompilerBase (/Users/workspace/vens/vens-test-tools-testcafe/node_modules/testcafe/src/compiler/test-file/api-based.js:32:20)
    at new ESNextTestFileCompiler (/Users/workspace/vens/vens-test-tools-testcafe/node_modules/testcafe/src/compiler/test-file/formats/es-next/compiler.js:12:1)
    at new GherkinTestcafeCompiler (/Users/workspace/vens/vens-test-tools-testcafe/node_modules/gherkin-testcafe/src/compiler.js:59:7)`

**Comment by mokone91** [comment]
same error(

**Comment by Arthy000** [comment]
Hello @eroetman & @mokone91 
I've finally reviewed the PR, and made a few additional requests.
Once that's done, I'll validate it.

I'll publish it right away so you can start using version 1.20 of TestCafe immediately.

**Comment by eroetman** [comment]
Hi, when do you plan to release this patch?

**Comment by Arthy000** [comment]
Hi @eroetman, I'm so sorry, I've been super busy lately and I completely forgot, doing it now

**Comment by eroetman** [comment]
Thanks!

**Comment by Arthy000** [comment]
Version 5.4.4 has been released, supports TestCafe 1.20
To keep using TC 1.19, don't update
